version: '3'
services:


  discovery-server:
    build:
      context: ./discovery-server
    ports:
      - "8761:8761"
    networks:
      - microservices

  config-server:
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    networks:
      - microservices
    depends_on:
      - discovery-server

  user-service:
    build:
      context: ./user-service
    ports:
      - "8880:8880"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka    
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    networks:
      - microservices
    depends_on:
      - discovery-server
      - config-server
    
  reservation-service:
    build:
      context: ./reservation-service
    ports:
      - "8881:8881"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka    
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    networks:
      - microservices
    depends_on:
      - config-server
      - discovery-server
    
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "9191:9191"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka    
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    networks:
      - microservices
    depends_on:
      - config-server
      - discovery-server
      - user-service
      - reservation-service

networks:
  microservices:
