version: '3'
services:

  config-server:
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    networks:
      - microservices

  user-service:
    build:
      context: ./user-service
    ports:
      - "8880:8880"
    networks:
      - microservices
    depends_on:
      - config-server

    
  # reservation-service:
  #   build:
  #     context: ./reservation-service
  #   ports:
  #     - "8881:8881"
  #   networks:
  #     - microservices
  #   depends_on:
  #     - config-server

networks:
  microservices:
