server:
  port: ${PORT:8880}
  servlet:
    context-path: /api/v1/user
    
spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/userDB
  
# spring:
#   application:
#     name: ${SPRING_APPLICATION_NAME}
#   data:
#     mongodb:
#       uri: ${SPRING_DATA_MONGODB_URI}
# server:
#   servlet:
#     context-path: ${SERVER_SERVLET_CONTEXT_PATH}