spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/momarious/spring-boot-spring-cloud-microservices.git
          username: ${git.username}
          password: ${git.password}
          clone-on-start: true
          search-paths: config-server/src/main/resources/applications/
server:
  port: 8010
