server:
  port: ${PORT:8880}
  servlet:
    context-path: /api/v1/user
    
spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

message: This is a message from the config server to the user-service
